Sprint 3/step 1
Gitaristium/stellar-burgers pull request #6
Opened 2023-04-07 07:40 UTC by Gitaristium

все изменения отражены в коммитах.
из основного:
-сверстаны страницы профиля и авторизации
-настроены маршруты
-настроена защита маршрутов
-настроены редюсеры для работы с API авторизации
-небольшие косметические улучшения

2023-04-07 08:22 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Оповещения о резульатах запросов
- Есть автологин и авторедирект
- В `ProtectedRoute ` реализована защита приватных и авторизационных роутов
- Реализован механизм обновления токена

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Юзер должен иметь возможность изменить данные не заполняя всю форму.
- Лого в хедере обычно делают ссылкой на главную страницу

**Можно лучше**
- accesToken лучше хранить в куках, а не `localStorage`

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-07 08:22 UTC, andryxxa93 commented on src/components/app/app.tsx
> +                        path="/login"
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-04-07 20:39 UTC, Gitaristium commented
поправил все замечания

2023-04-08 09:26 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-08 11:20 UTC, merged